Numpy

In [3]:
import numpy as np

In [5]:
# Energy consumption in MWh for differenct renewable sources: Solar, wind, hydropower, geothermal
ec = [1200, 3400, 2900, 1800, 2500]
energy_consumption = np.array(ec)

print("Energy Consumption (in MWh) for Different Renewable Sources:")
print(energy_consumption)

Energy Consumption (in MWh) for Different Renewable Sources:
[1200 3400 2900 1800 2500]


In [10]:
A = np.ones(4)
print(A)
A2 = np.ones((2,3))
print(A2)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
M = np.zeros(4)
print(M)
M2 = np.zeros((3,3))
print(M2)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# Identity matrix
M = np.identity(4)
print(M)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# Calculate total energy consumption
total_consumption = np.sum(energy_consumption)
print(f"Total Energy Consumption: {total_consumption} MWh")

Total Energy Consumption: 11800 MWh


In [21]:
mean_consumption = np.mean(energy_consumption)
print(f"Mean Energy Consumption: {mean_consumption} MWh")

Mean Energy Consumption: 2360.0 MWh


In [23]:
std_consumption = np.std(energy_consumption)
print(f"SD of Energy Consumption: {std_consumption} MWh")

SD of Energy Consumption: 781.2809993849844 MWh


Reshaping the Array

In [35]:
# Reshape the array (to 5 rows and 1 column)
# Reshapes tha array into desired rows and columns
energy_consumption2 = np.array([1200, 3400, 2900, 1800, 2500, 1800])
reshaped_array = energy_consumption2.reshape((3,2))
print("Reshaped Energy Consumption Arra (3x2): ")
print(reshaped_array)

Reshaped Energy Consumption Arra (3x2): 
[[1200 3400]
 [2900 1800]
 [2500 1800]]


In [29]:
# flatten
reshaped_array.flatten()

array([1200, 3400, 2900, 1800, 2500, 1800])

In [37]:
# transpose
# reshaped_array.transpose()
reshaped_array.T

array([[1200, 2900, 2500],
       [3400, 1800, 1800]])

In [40]:
# Duplicate value is added if needed
resize_array = np.resize(reshaped_array, (3,3))
resize_array

array([[1200, 3400, 2900],
       [1800, 2500, 1800],
       [1200, 3400, 2900]])